import React from "react";
export const metadata = { title: "Friends Colony Phase-1"
}; export default function Page() { return ( <main className="max-w-4xl mx-auto py-12 px-6"> <h1 className="text-3xl font-bold mb-2">Friends Colony Phase-1</h1> <p className="text-sm text-gray-600 mb-4">1000–2000 sq.ft • Ownership: Freehold • Price: ₹16800 Per sq/yard onwards • Status: Construction-ready</p> <div className="prose"> <p>Friends Colony Phase-1 is a well-organized residential pocket that balances community living with easy connectivity. Plots are laid out along clear streets with good access to main roads and public transport. The area is practical for families who value quick commutes and nearby conveniences- markets, clinics, and schools are all within easy reach. Because the layout is clean and construction-ready, many buyers can begin building right away, making it a favourite for those who want a faster move-in timeline.</p> <p>What you get- travel &amp; access
Nearest major expressway / approach: ~5 minutes to Delhi–Dehradun Expressway.</p> <p>Dehradun ISBT / central bus hub: ~25-30 minutes.</p> <p>Dehradun Railway Station: ~25 minutes.</p> <p>Jolly Grant Airport: ~35 minutes.</p> <p>Hospitals / clinics: Local clinics and multi-speciality hospitals are typically 10 minutes.</p> <p>Schools &amp; coaching centres: Multiple established schools and coaching institutes in ~10–20 minutes.</p> <p>Lifestyle &amp; convenience
Friends Colony is for families who value both neighbourhood warmth and practical mobility. The community layout encourages social living- street-side trees, safe play areas, and neighbors who invest in long-term homes.</p> <p>Investment rationale
Because plots are ready for immediate construction, buyers can start development right away- accelerating utility connections and rental/resale potential for investors targeting short-to-medium term returns.</p> <p>Assurance
Complete verification pack on request with title search, layout approval and a step-by-step registration guide.
</p> </div> </main> );
}
