import React from "react";
export const metadata = { title: "Bajrang Vatika - The Private Retreat"
}; export default function Page() { return ( <main className="max-w-4xl mx-auto py-12 px-6"> <h1 className="text-3xl font-bold mb-2">Bajrang Vatika - The Private Retreat</h1> <p className="text-sm text-gray-600 mb-4">1200–2400 sq.ft • Ownership: Freehold • Price: ₹16800 Per sq/yard onwards • Status: Ready-to-develop</p> <div className="prose"> <p>Bajrang Vatika is a calm, family-friendly residential layout designed for buyers who want everyday convenience without the city rush. The roads are motorable and well-defined, plot boundaries are clear, and basic utilities are accessible- making it straightforward to plan and build. The neighbourhood has local shops, primary schools, and public transport within short distance, so daily needs are easy to meet. Because the area is still growing, you can buy at an attractive price now and benefit from steady appreciation as infrastructure improves.</p> <p>What you get- travel &amp; access
Dehradun ISBT (Inter-State Bus Terminal): ~15 minutes.</p> <p>Dehradun Railway Station: ~20 minutes.</p> <p>Jolly Grant Airport (Dehradun): ~30 minutes.</p> <p>Nearest hospitals / healthcare: Kailash Hospital, Graphic Era Hospital ~ 5–20 minutes.</p> <p>Nearby schools &amp; colleges: Doon Global School, Shubharti Medical College 5–20 minutes.</p> <p>Lifestyle &amp; convenience
Bajrang Vatika suits buyers who want to escape traffic without losing access to essential services. Morning walks, private gardens and space for personal landscaping are core to life here. Nearby schools, neighbourhood markets and easy bus access mean daily needs are effortless.</p> <p>Investment rationale
With limited supply in the immediate pocket and improving local infrastructure, Bajrang Vatika offers steady appreciation potential for conservative investors and family offices who prefer low-volatility land parcels.</p> <p>Assurance
Every plot is sold with a verified title pack; we assist with registration, transfer and construction-permission guidance.
</p> </div> </main> );
}
